//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TMat.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_TMatTYPE                    130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DLG_CONFIG                  310
#define IDR_TOOLBAR1                    311
#define IDR_MENU1                       313
#define IDR_MAINMENU                    313
#define IDC_CURSOR_SEARCH               315
#define IDC_EDIT_SRCPATH                1000
#define IDC_EDIT_LOGPATH                1001
#define IDC_BUTTON_BROWSER              1002
#define ID_FILE_CONFIGURATION           32771
#define IDR_TOOLBAR_24                  32772
#define ID_BUTTON32773                  32773
#define ID_BUTTON32774                  32774
#define ID_FILE_EXIT                    32775
#define ID_FILE                         32776
#define ID_FILE_EXIT32777               32777
#define ID_PROJECT_ADDIMAGE             32778
#define ID_PROJECT_REMOVEIMAGE          32779
#define ID_VIEW_2DVIEW                  32780
#define ID_VIEW_3DVIEW                  32781
#define ID_VIEW_INITIALIZE              32782
#define ID_PROJECT_SEARCH               32783
#define ID_VIEW_LOGVIEW                 32784
#define ID_PROJECT_CLEARRESULT          32785
#define ID_ANALYZE_EXTRACTTEXT          32786
#define ID_PROJECT_CONFIGURATION        32787
#define ID_FILE_OPENFILE                32788
#define ID_TOOLS                        32789
#define ID_HELP32790                    32790
#define ID_HELP_ABOUT                   32791
#define ID_ANALYZE_UPLOADRESULT         32792
#define ID_ANALYZE_DOWNLOADRESULT       32793
#define ID_PROJECT_KEYWORDSEARCH        32794
#define ID_VIEW_LOGVIEW_                32795
#define ID_TOOLS_CUTSEARCH              32796
#define ID_TOOLS_KEYWORDSEARCH          32797
#define ID_TOOLS_CLEARRESULT            32798
#define ID_PROJECT_KEYWORDSEARCH_       32799
#define ID_ANALYZE_UPLOADRESULT_        32800
#define ID_ANALYZE_DOWNLOADRESULT_      32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
